# Generated by Django 2.1 on 2018-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('party_type', models.CharField(max_length=10)),
                ('party_location', models.CharField(max_length=5)),
                ('party_address', models.CharField(max_length=200)),
                ('level1', models.CharField(max_length=100)),
                ('level2', models.CharField(max_length=100)),
                ('level3', models.CharField(max_length=100)),
                ('level4', models.CharField(max_length=100)),
            ],
        ),
    ]
