# Generated by Django 2.1 on 2018-08-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_uom', models.CharField(max_length=3)),
                ('grosswgt_uom', models.CharField(max_length=3)),
                ('netwgt_uom', models.CharField(max_length=3)),
                ('commodity', models.CharField(max_length=15)),
                ('hscode', models.CharField(max_length=15)),
                ('level1', models.CharField(max_length=100)),
                ('level2', models.CharField(max_length=100)),
                ('level3', models.CharField(max_length=100)),
                ('level4', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pkg', models.CharField(max_length=10)),
                ('doc_pkg', models.CharField(max_length=10)),
                ('vol_uom', models.CharField(max_length=3)),
                ('grosswgt_uom', models.CharField(max_length=3)),
                ('netwgt_uom', models.CharField(max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='party',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Company'),
        ),
    ]
