# Generated by Django 2.1 on 2018-08-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20180815_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
