# Generated by Django 2.1 on 2018-08-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_remove_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('SHIPPER', 'Shipper Label'), ('LSP', 'LSP Label')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
