# Generated by Django 2.0.4 on 2018-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_auto_20180816_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationkeyword',
            name='keyword',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
