# Generated by Django 2.1 on 2018-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_locationkeyword_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grosswgt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='netwgt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='vol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='grosswgt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='netwgt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='vol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
