# Generated by Django 2.0.6 on 2018-06-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0002_auto_20180618_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoOwnerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Section')),
            ],
        ),
        migrations.RenameField(
            model_name='sectioncost',
            old_name='author',
            new_name='executor',
        ),
        migrations.AddField(
            model_name='match',
            name='section_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.SectionCost'),
        ),
    ]
