# Generated by Django 2.0.4 on 2018-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biztype', models.CharField(choices=[('EXPORT', 'Export biztype'), ('IMPORT', 'Import biztype')], max_length=10)),
                ('rdd', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open Status'), ('PROCEEDING', 'Proceeding'), ('COMPLETE', 'Complete')], max_length=10)),
            ],
        ),
    ]
